export const SET_SEARCH_QUERY = 'setSearchQuery';
export const REMOVE_SEARCH_QUERY = 'removeSearchQuery';

// CART
export const ADD_CART = 'ADD_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const ADD_TO_USER_CART = 'ADD_TO_USER_CART';
export const ADD_TO_ENSEMBLE_CART = 'ADD_TO_ENSEMBLE_CART';
export const ADD_TO_PUBLISHER_CART = 'ADD_TO_PUBLISHER_CART';
export const ADD_TO_INSTITUTION_CART = 'ADD_TO_INSTITUTION_CART';
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR';
export const GET_CART_PRODUCTS = 'GET_CART_PRODUCTS';
export const GET_CART_PRODUCTS_SUCCESS = 'GET_CART_PRODUCTS_SUCCESS';
export const GET_CART_PRODUCTS_FAILED = 'GET_CART_PRODUCTS_FAILED';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const REMOVE_FROM_USER_CART = 'REMOVE_FROM_USER_CART';
export const REMOVE_FROM_ENSEMBLE_CART = 'REMOVE_FROM_ENSEMBLE_CART';
export const REMOVE_FROM_PUBLISHER_CART = 'REMOVE_FROM_PUBLISHER_CART';
export const SHOW_CHECKOUT_SCREEN = 'SHOW_CHECKOUT_SCREEN';
export const HIDE_CHECKOUT_SCREEN = 'HIDE_CHECKOUT_SCREEN';
export const CLEAR_USER_CART = 'CLEAR_USER_CART';
export const CLEAR_ENSEMBLE_CART = 'CLEAR_ENSEMBLE_CART';
export const CLEAR_PUBLISHER_CART = 'CLEAR_PUBLISHER_CART';
export const CLEAR_INSTITUTION_CART = 'CLEAR_INSTITUTION_CART';

// PRODUCTS
export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const CHANGE_ACTIVE_PRODUCT = 'CHANGE_ACTIVE_PRODUCT';
